### ISSUE TITLE
[FEATURE] [DUPLICATE]Add Traps and Vehicles to the NPC tab

### ISSUE THREAD

**Issue by EthanDunning** [msprijatelj/4e-module-generator-portable-compendium#14]
As you probably know, the portable compendium has a ton of traps and Vehicles, both of which are supported by FG under the npc table, you can choose between creature, trap, and vehicle when creating a new creature. I would like to request that you add support for the creation of these.

**Comment by msprijatelj** [comment]
Traps and Hazards will be covered by #9.  As for Vehicles, using the Beta 30 version of the Portable Compendium, I cannot find non-glossary entries for vehicles like those introduced in the Adventurer's Vault.  If these are available in a different version of the Portable Compendium, please let me know and I'll investigate adding it in.

**Comment by EthanDunning** [comment]
Ah i am terribly sorry, I seemed to have overlooked that. I will take a closer look before suggesting something you have already covered. I actually only have beta 29, do you know where I could get my hands on beta 30? I much like it for myself to be used with your tools.

**Comment by skelekon** [comment]
(I just realized I have been using v.29 as well this whole time.)

A.V. vehicles in v.29 are also just Glossary entries with a text description and no stats, so probably not worth generating.

**Comment by msprijatelj** [comment]
V29 works well enough then haha. Not sure where I picked up v30 but I know it’s out there. Closing this issue for now.
