### ISSUE TITLE
[FEATURE] .dnd4e to FG converter

### ISSUE THREAD

**Issue by EthanDunning** [msprijatelj/4e-module-generator-portable-compendium#16]
**Is your feature request related to a problem? Please describe.**
One thing that I think would just put the icing on the cake for this repository is creating a modern .dnd4e to FG xml character converter. 
I know this doesnt have much to do with the Portable Compendium, but having parsed that data, makes this actually doable.

The old character FG converter doesn't work very well since there were never any official .mods for 4e and the application hasnt been taken care of in years. You can still use it, but all the feats and powers come out blank, and the skills are absent entirely, as well as some other math errors. 

**Describe the solution you'd like**
.dnd4e character files themselves are just a renamed xml file. I think now that we can data for what all of the things in the character sheet are, like poowers, feats, items, etc, we use the data we've already generated to fill in the blanks. The old character converter fails because it needs to look up ddi data, but since we already have everything it needs, we can just have it do a search for those items.
This will tie in with importing more of the glossary data from the Portable Compendium to get things like skills and such, since those currently arent something that is produced with the current code.

heres a file with some examples of what I mean
EDIT: added a version of the character that I fixed using the portable compendium data

[Example.zip](https://github.com/msprijatelj/4e-module-generator-portable-compendium/files/8495547/Example.zip)

**Comment by msprijatelj** [comment]
I am more inclined to keep this repository focused on the Portable Compendium. That said, this repo is under a GPL license, so if the code is reusable, someone who wants to tackle .dnd4e files can use this repo as a jumping-off-point.

**Comment by msprijatelj** [comment]
Also, again, please refrain from sharing 4e content with exact rules text from WotC materials.  I'm being strict about this to avoid anyone coming down on our heads for sharing 4e content.  You can use the content for personal use, but publicly posting the data on GitHub is outside the realm of personal use.

If you want to post example files to demonstrate the structure of the files being used, **_please_** remove 4e rules text ahead of time.  Names of traits, powers, etc. is okay, but the exact rules text itself is not.
